version: "3.3"

services:

  # Docker registry
  registry:
    image: registry:
    volumes:
      - registry:/registry
    networks:
        - registry      
    deploy:
      mode: replicated
      replicas: 1
    ports:
      - "5000:5000"
  
# Volumes
volumes:
  registry:

# Networks
networks:
  registry:
    driver: overlay
